/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook.ui;

import phonebook.Main;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import phonebook.db.entity.Contact;

/**
 *
 * @author homefulloflove
 */
public class TableFrame extends javax.swing.JFrame {

    private String connection;
    private DatabaseTableModel dbtm;
    private ArrayList<String> columnNames;

    /**
     * Creates new form TableFrame
     */
    public TableFrame() {
        initComponents();

        setLocationRelativeTo(null);

        connection = "jdbc:sqlite:database.sl3";
        loadData();

    }

    private void loadData() {
        dbtm = new DatabaseTableModel(false);

        try (Connection conn = DriverManager.getConnection(connection)) {

//            columnNames = new ArrayList<>();
            Statement stmt = conn.createStatement();
//            String sqlColNames = "PRAGMA TABLE_INFO('contacts')";
//            ResultSet rseq = stmt.executeQuery(sqlColNames);
//            while (rseq.next()) {
//                columnNames.add(rseq.getString(2));
//                System.out.println(rseq.getString(2));
//            }

            String sqlData = "SELECT * FROM contacts";
            ResultSet rs = stmt.executeQuery(sqlData);
            try {
                dbtm.setDataSource(rs);
                jtData.setModel(dbtm);
            } catch (Exception ex) {
                Logger.getLogger(TableFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Main.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jpmData = new javax.swing.JPopupMenu();
        jmiDataEditContact = new javax.swing.JMenuItem();
        jmiDataDeleteContact = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmContacts = new javax.swing.JMenu();
        jmiAddContact = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jmiDataEditContact.setText("Edit...");
        jmiDataEditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDataEditContactActionPerformed(evt);
            }
        });
        jpmData.add(jmiDataEditContact);

        jmiDataDeleteContact.setText("Delete");
        jmiDataDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDataDeleteContactActionPerformed(evt);
            }
        });
        jpmData.add(jmiDataDeleteContact);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contacts");

        jtData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtData.setComponentPopupMenu(jpmData);
        jScrollPane1.setViewportView(jtData);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jmContacts.setText("Contacts");

        jmiAddContact.setText("Add...");
        jmiAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddContactActionPerformed(evt);
            }
        });
        jmContacts.add(jmiAddContact);

        jMenuBar1.add(jmContacts);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void saveContact(Contact cont) {

        String sql = "INSERT INTO contacts VALUES(null, ?, ?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(connection)) {
            PreparedStatement prepareStatement = conn.prepareStatement(sql);
            prepareStatement.setString(1, cont.getFullName());
            prepareStatement.setString(2, cont.getPhoneNum());
            prepareStatement.setString(3, cont.getEmail());
            prepareStatement.setString(4, cont.getSkype());
            prepareStatement.setString(5, cont.getImage());

            prepareStatement.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(TableFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        loadData();
    }

    private void jmiAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddContactActionPerformed

        AddContactFrame contactFrame = new AddContactFrame(this);
        contactFrame.setLocationRelativeTo(this);
        contactFrame.setVisible(true);

    }//GEN-LAST:event_jmiAddContactActionPerformed

    private Contact getContact(int id) {
        String sql = "SELECT * FROM contacts WHERE id = " + id;

        try (Connection conn = DriverManager.getConnection(connection)) {
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);

            if (rs.next()) {
                String name = rs.getString("name");
                String phone = rs.getString("phone_number");
                String mail = rs.getString("email");
                String skype = rs.getString("skype");
                String image = rs.getString("image");

                return new Contact(name, phone, mail, skype, image);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TableFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    private void jmiDataEditContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDataEditContactActionPerformed

        int row = jtData.getSelectedRow();

        int id = (int) jtData.getValueAt(row, 0);
        Contact contact = getContact(id);

        AddContactFrame contactFrame = new AddContactFrame(this, contact);
        contactFrame.setLocationRelativeTo(this);
        contactFrame.setVisible(true);

    }//GEN-LAST:event_jmiDataEditContactActionPerformed

    private void jmiDataDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDataDeleteContactActionPerformed
        int row = jtData.getSelectedRow();
        int id = (int) jtData.getValueAt(row, 0);
        String sql = "DELETE FROM contacts WHERE id = " + id;

        try (Connection conn = DriverManager.getConnection(connection)) {
            Statement stat = conn.createStatement();
            stat.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(TableFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
    }//GEN-LAST:event_jmiDataDeleteContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmContacts;
    private javax.swing.JMenuItem jmiAddContact;
    private javax.swing.JMenuItem jmiDataDeleteContact;
    private javax.swing.JMenuItem jmiDataEditContact;
    private javax.swing.JPopupMenu jpmData;
    private javax.swing.JTable jtData;
    // End of variables declaration//GEN-END:variables
}
